### PR TITLE
Laravel 5.4

### PR DESCRIPTION
**Pull request by shaunthegeek**
Hello everyone, I have writed a new version of wifidog-auth using laravel 5.4(PHP 5.6 #17).
CI tesing and lint is success: https://circleci.com/gh/sinkcup/wifidog-auth/9

# Wifidog Auth (Laravel 5.4)

This project provides a auth server for wifidog. For API details, please see the [WiFiDog Protocol V1](http://dev.wifidog.org/wiki/doc/developer/WiFiDogProtocol_V1).

## Pages

- login/
- portal/ 
- messages/ OR gw\_message.php

## Apis

- ping/
- auth/

## Getting Started

```
composer install
```

## Tech

- PHP Framework: [Laravel 5.4](https://laravel.com/docs/5.4/)
- Coding standard: following [PSR2](http://www.php-fig.org/psr/psr-2/). run `./lint.sh` to check.
- Unit Test: using PHPUnit. run `./phpunit.sh`.
- CI: using [circleci.com](https://circleci.com/)

### CODE REVIEW

**Comment by shaunthegeek** [comment]
is there anyone? @benoitg @fproulx @networkfusion

**Comment by benoitg** [comment]
@sinkcup Exactly what are your asking us to do?  You've wiped all traces of the old code, and all traces of the authors or licence.  I presume you want to take over the project with an admittedly modern codebase, but one that only implements a very small subset of features or documentation.

We've had one project before (authpuppy) pretend it would do exactly that.  It achieved neither feature parity nor attracted any development community.  What it did manage to do however, is pretty much wipe out the existing wifidog development community.

You want your own project under the wifidog org on github (Say wifidog/wifidog-auth-laravel)?  If so, you got it! 

I am however, not "officially" blessing a successor, far less wiping out the history of a project that so many spent countless hours on, if only for historical reasons.

**Comment by chrisbalicki** [comment]
@sinkcup - I would love to see this! can you add as a new project under Wifidog?

**Comment by shaunthegeek** [comment]
@rootcause89 - I have created a new project: 
https://github.com/sinkcup/wifidog-auth-laravel

**Comment by benoitg** [comment]
Ok, created https://github.com/wifidog/wifidog-auth-laravel , and @sinkcup has full control of it, and of the associated team.  Happy coding!

**Pull request closed without merging**
